---
title: "Brute Force Knapsack"
author: "Fahad Hameed Ugurcan Lacin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In this package we are implementing a package which is for Lab 6.


```{r}
knapsack_objects <-
data.frame(
  w=sample(1:4000, size = 2000, replace = TRUE),
  v=runif(n = 2000, 0, 10000))
```

Brute force knapsack implementation.

```{r}
brute_force_knapsack <- function(x,W){
  
  listOfCombinations <- list()
  for(i in 1:nrow(x)){
    listOfCombinations[[i]] <- combn(rownames(x), i, paste, collapse = " ")
  }
  
  listOfWeights <- list()
  for(i in 1:nrow(x)){
    listOfWeights[[i]] <- combn(x$w, i,sum)
  }
  
  listOfValues <- list()
  for(i in 1:nrow(x)){
    listOfValues[[i]] <- combn(x$v, i,sum)
  }

  vectorOfCombinations <- unlist(listOfCombinations)
  vectorOfWeights <- unlist(listOfWeights)
  vectorOfValues <- round(unlist(listOfValues),0)
  
  weightsIndexesUnderTheCapacity <- which(vectorOfWeights < W)
  validValues <- vectorOfValues[weightsIndexesUnderTheCapacity]
  maximumValidValue <- max(validValues)
  
  validValuesIndexesInCombinationsVector <- which(vectorOfValues == maximumValidValue)
  validCombination <- vectorOfCombinations[validValuesIndexesInCombinationsVector]
  
  bestCombinationList <- list(value = maximumValidValue, elements = validCombination)
  return(bestCombinationList)
}
```

**_Question_** How much time does it takes to run the algorithm for n = 16 objects?

```{r,echo=FALSE,results="hide"}
ptm <- proc.time()
brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500)
result <- proc.time() - ptm
```

```{r,echo=FALSE}
result
```


